// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"go-wire-mongo/app"
	"go-wire-mongo/app/author"
	"go-wire-mongo/app/book"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func AppModule() app.AppController {
	appController := app.ProvideAppController()
	return appController
}

func AuthorModule(db *mongo.Database) author.AuthorController {
	authorRepository := author.ProvideAuthorRepository(db)
	authorService := author.ProvideAuthorService(authorRepository)
	authorController := author.ProvideAuthorController(authorService)
	return authorController
}

func BookModule(db *mongo.Database) book.BookController {
	bookRepository := book.ProvideBookRepository(db)
	authorRepository := author.ProvideAuthorRepository(db)
	authorService := author.ProvideAuthorService(authorRepository)
	bookService := book.ProvideBookService(bookRepository, authorService)
	bookController := book.ProvideBookController(bookService)
	return bookController
}
